### ISSUE TITLE
snakemake >= 7.18.2 crashes renaming anonymous rules in some cases

### ISSUE THREAD

**Issue by cnluzon** [NBISweden/minute#159]
I am currently working on some fixes for the MultiQC reporting. While doing so, I wanted to update MultiQC version to its most recent, since the issue I submitted: https://github.com/ewels/MultiQC/issues/1645 seems to have been fixed.

I created a fresh environment for this with MultiQC 1.13, but now when I run with the test data I get:

```
UnknownRuleException:   
There is no rule named compute_scaling_factors_group_group2.
```

When comparing I notice that `snakemake-minimal` also got updated to 7.18.2. With the older environment the workflow succeeds, so I guess there is some change in how snakemake handles rule groups or rule names that makes this crash now, but I am uncertain about whether it is a workflow issue, or a snakemake issue. For the time being I will probably pin snakemake version on `environment.yaml` to one that works until I find out what the origin of the issue is.

Additional note on this is that there is some intermediate version of `snakemake-minimal` that trashes output from failed rules under the `run:` directive: https://github.com/snakemake/snakemake/issues/1698 that gives me headaches if something crashes there, so I will probably pin the version on some intermediate that makes both things work (if such configuration exists).

**Comment by hejincan** [comment]
> I am currently working on some fixes for the MultiQC reporting. While doing so, I wanted to update MultiQC version to its most recent, since the issue I submitted: [ewels/MultiQC#1645](https://github.com/ewels/MultiQC/issues/1645) seems to have been fixed.
> 
> I created a fresh environment for this with MultiQC 1.13, but now when I run with the test data I get:
> 
> ```
> UnknownRuleException:   
> There is no rule named compute_scaling_factors_group_group2.
> ```
> 
> When comparing I notice that `snakemake-minimal` also got updated to 7.18.2. With the older environment the workflow succeeds, so I guess there is some change in how snakemake handles rule groups or rule names that makes this crash now, but I am uncertain about whether it is a workflow issue, or a snakemake issue. For the time being I will probably pin snakemake version on `environment.yaml` to one that works until I find out what the origin of the issue is.
> 
> Additional note on this is that there is some intermediate version of `snakemake-minimal` that trashes output from failed rules under the `run:` directive: [snakemake/snakemake#1698](https://github.com/snakemake/snakemake/issues/1698) that gives me headaches if something crashes there, so I will probably pin the version on some intermediate that makes both things work (if such configuration exists).

Hello！I got the same issue when running on my own data. I wonder have you fix this problem? Which version of snakemake can work ?

**Comment by cnluzon** [comment]
Hi! The workaround I found is to downgrade snakemake in the conda environment to an older version that works. I have found that `snakemake-minimal =7.16.0` does not raise this issue. So you can either manually do this on your environment (something like `conda install snakemake-minimal=7.16.0`. You might need to uninstall the previous version before) or update the `environment.yaml` file with this line and create another envirnoment with this.

There is an ongoing PR  #160 that among other things pins snakemake version to that one until I find out a more permanent fix for this, so eventually this will be updated in the main branch.

**Comment by cnluzon** [comment]
I have been looking at this issue for a while and it is very difficult to debug. Oddly enough, it only crashes with the renaming of the scaling rules but not the demultiplexing ones. 

I feel like the inherent recursivity of running snakemake makes it complicated to follow up the workflow object, and maybe it should not be modified directly accessing its variables. The reason we do this is mostly cosmetic (the DAG table of rules gets a few numbered rules on the initial summary), and I would prefer the workflow not to crash due to that, so I am inclined to remove both those rule name setting functions and just letting the workflow work with the anonymous rule numbers while we find a better solution to this, so we can keep up with an up-to-date version of snakemake, which I think is preferable.
